// Generated by GamEngine. You can safely edit this script.
#include "PlayerController.h"

#include <Engine/ECS/Components/CameraComponent.h>
#include <Engine/Input/Input.h>
#include <Engine/Scene/Components/IdentityComponents.h>
#include <Engine/Scripting/ScriptRegistry.h>

#include <cmath>
#include <unordered_map>

namespace {
constexpr float MovementSpeed = 6.0F;
constexpr float JumpSpeed = 6.5F;
constexpr float GroundVelocityTolerance = 0.15F;
// Keep this in sync with CameraController's gameplay mouse sensitivity.
constexpr float MouseSensitivity = 0.25F;
constexpr float Zero = 0.0F;
}

void PlayerController::onUpdate(const float deltaTime) {
    (void)deltaTime;

    // A player normally owns its physics body. Keep the child lookup as a
    // fallback for scenes created with the older Player/Capsule layout.
    Engine::Actor body = actor();
    if (!body.hasRigidbody()) {
        for (const Engine::Actor& child : children()) {
            if (child.hasRigidbody()) {
                body = child;
                break;
            }
        }
    }
    if (!body.valid()) return;

    // Keep this yaw calculation identical to the renderer's camera setup.
    // Transform matrices use a different rotation convention for their local
    // axes, so deriving the movement vector from that matrix flips Z.
    float movementYaw = body.rotation().y();
    bool foundPrimaryCamera = false;
    std::unordered_map<Engine::UUID, Engine::Entity> entitiesByUuid;
    registry().view<Engine::UUIDComponent>([&](const Engine::Entity entity,
                                                const Engine::UUIDComponent& uuid) {
        entitiesByUuid.emplace(uuid.value, entity);
    });
    registry().view<Engine::CameraComponent, Engine::Transform, Engine::UUIDComponent>(
        [&](const Engine::Entity entity, const Engine::CameraComponent& camera,
            const Engine::Transform& cameraTransform, const Engine::UUIDComponent&) {
            if (foundPrimaryCamera || !camera.primary) return;

            // CameraController applies this frame's mouse delta after scripts.
            // Predict its local yaw here, then compose the complete hierarchy
            // exactly as the renderer does for the displayed Game View.
            movementYaw = cameraTransform.rotation.y() +
                          Engine::Input::mouseDelta().x() * MouseSensitivity;
            Engine::Entity current = entity;
            while (registry().has<Engine::ParentComponent>(current)) {
                const Engine::UUID parentUuid = registry().get<Engine::ParentComponent>(current).parent;
                const auto parent = entitiesByUuid.find(parentUuid);
                if (parent == entitiesByUuid.end() || !registry().has<Engine::Transform>(parent->second)) break;
                current = parent->second;
                movementYaw += registry().get<Engine::Transform>(current).rotation.y();
            }
            foundPrimaryCamera = true;
        });

    const float yawRadians = movementYaw * Engine::Pi / 180.0F;
    const Engine::Vec3 forward{std::cos(yawRadians), Zero, std::sin(yawRadians)};
    const Engine::Vec3 right{-forward.z(), Zero, forward.x()};
    Engine::Vec3 movement{};
    if (Engine::Input::keyDown(Engine::KeyCode::W)) movement += forward;
    if (Engine::Input::keyDown(Engine::KeyCode::S)) movement -= forward;
    if (Engine::Input::keyDown(Engine::KeyCode::D)) movement += right;
    if (Engine::Input::keyDown(Engine::KeyCode::A)) movement -= right;

    Engine::Vec3 velocity = body.velocity();
    if (movement.length() > 0.0F) movement = movement.normalized() * MovementSpeed;
    velocity.setX(movement.x());
    velocity.setZ(movement.z());

    // A stationary vertical velocity is the state PhysX reports while the
    // capsule rests on the ground. This prevents normal repeated air jumps.
    if (Engine::Input::keyPressed(Engine::KeyCode::Space) &&
        std::abs(velocity.y()) <= GroundVelocityTolerance) {
        velocity.setY(JumpSpeed);
    }
    body.setVelocity(velocity);
}

ENGINE_REGISTER_SCRIPT(PlayerController);
