#pragma once

#include <cstdint>

namespace Engine {

    /**
     * @brief Unique identifier used by the entity-component system.
     *
     * Entity value zero is reserved for @ref NullEntity. Valid entities are
     * generated by Registry.
     */
    using Entity = std::uint64_t;

    /**
     * @brief Sentinel representing an invalid or absent entity.
     */
    constexpr Entity NullEntity = 0;

}
