#pragma once

#include <cstdint>

namespace Engine {
    /**
     * @brief Unique identifier used by the entity-component system.
     *
     * Entity value zero is reserved for @ref NullEntity. Valid entities are
     * generated by Registry.
     */
    using Entity = std::uint64_t;

    /**
     * @brief Stable identifier owned by a GameObject.
     *
     * Unlike Entity, an ObjectId is not recycled when the object's ECS
     * entity is destroyed.
     */
    using ObjectId = std::uint64_t;

    constexpr std::uint32_t entityIndex(const Entity entity) noexcept {
        return static_cast<std::uint32_t>(entity);
    }

    constexpr std::uint32_t entityGeneration(const Entity entity) noexcept {
        return static_cast<std::uint32_t>(entity >> 32U); //NOLINT
    }

    constexpr Entity makeEntity(const std::uint32_t index,
                                const std::uint32_t generation) noexcept {
        return (static_cast<Entity>(generation) << 32U) | index; //NOLINT
    }

    /**
     * @brief Sentinel representing an invalid or absent entity.
     */
    constexpr Entity NullEntity = 0;

    constexpr ObjectId NullObjectId = 0;
}
