#pragma once

#include <cstdint>

namespace Engine {

    /**
     * @brief Unique identifier used by the entity-component system.
     *
     * Entity value zero is reserved for @ref NullEntity. Valid entities are
     * generated by Registry.
     */
    using Entity = std::uint64_t;

    constexpr std::uint32_t entityIndex(const Entity entity) noexcept {
        return static_cast<std::uint32_t>(entity);
    }

    constexpr std::uint32_t entityGeneration(const Entity entity) noexcept {
        return static_cast<std::uint32_t>(entity >> 32u);
    }

    constexpr Entity makeEntity(const std::uint32_t index,
                                const std::uint32_t generation) noexcept {
        return (static_cast<Entity>(generation) << 32u) | index;
    }

    /**
     * @brief Sentinel representing an invalid or absent entity.
     */
    constexpr Entity NullEntity = 0;

}
