// Generated by GamEngine. You can safely edit this script.
#pragma once
#include <Engine/Scripting/Script.h>

class PlayerController final : public Engine::Script {
public:
    void onCreate() override {}
    void onEnable() override {}
    void onUpdate(float deltaTime) override { (void)deltaTime; }
    void onDisable() override {}
    void onDestroy() override {}
};
