#include "Engine/Renderer/Passes/GtaoPass.h"
#include "Engine/Renderer/shader_loader.h"

#include <algorithm>
#include <glm/glm.hpp>
#include <stdexcept>

namespace Engine {
namespace {
struct RawSettings { glm::vec2 projectionScale; float fullWidth, fullHeight, radiusView, falloff; };
struct FilterSettings { float inverseWidth, inverseHeight, depthSigma, normalSigma; glm::vec2 direction; };
struct TemporalSettings { float inverseWidth, inverseHeight, historyWeight, padding; };
struct UpsampleSettings { float inverseFullWidth, inverseFullHeight, depthSigma, padding; float inverseHalfWidth, inverseHalfHeight, padding0, padding1; };
struct LinearizeSettings { glm::mat4 inverseProjection; };
constexpr VkFormat AoFormat = VK_FORMAT_R16_SFLOAT;
constexpr VkFormat HistoryFormat = VK_FORMAT_R16G16_SFLOAT;
constexpr VkFormat AuxiliaryFormat = VK_FORMAT_R16G16B16A16_SFLOAT;
constexpr VkFormat FullAoFormat = VK_FORMAT_R8_UNORM;
}

GtaoPass::~GtaoPass() { destroy(); }

void GtaoPass::create(const VkPhysicalDevice physical, const VkDevice device, const VkExtent2D fullExtent,
                      const VmaAllocator allocator, Assets::AssetManager& assets) {
    if (!device || !fullExtent.width || !fullExtent.height) throw std::invalid_argument("GTAO requires a valid extent");
    destroy(); device_ = device; allocator_ = allocator; fullExtent_ = fullExtent;
    halfExtent_ = {std::max(1U, fullExtent.width / 2U), std::max(1U, fullExtent.height / 2U)};
    try {
        raw_.create(physical, device_, halfExtent_, allocator, VK_FILTER_NEAREST, AoFormat);
        auxiliary_.create(physical, device_, halfExtent_, allocator, VK_FILTER_NEAREST, AuxiliaryFormat);
        spatial_.create(physical, device_, halfExtent_, allocator, VK_FILTER_NEAREST, AoFormat);
        filtered_.create(physical, device_, halfExtent_, allocator, VK_FILTER_NEAREST, AoFormat);
        for (auto& image : history_) image.create(physical, device_, halfExtent_, allocator, VK_FILTER_NEAREST, HistoryFormat);
        full_.create(physical, device_, fullExtent_, allocator, VK_FILTER_LINEAR, FullAoFormat);
        linearDepthMipCount_ = 1;
        for (auto dimension = std::max(fullExtent_.width, fullExtent_.height); dimension > 1; dimension >>= 1) ++linearDepthMipCount_;
        VkImageCreateInfo depthImage{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO}; depthImage.imageType=VK_IMAGE_TYPE_2D; depthImage.format=VK_FORMAT_R16_SFLOAT; depthImage.extent={fullExtent_.width,fullExtent_.height,1}; depthImage.mipLevels=linearDepthMipCount_; depthImage.arrayLayers=1; depthImage.samples=VK_SAMPLE_COUNT_1_BIT; depthImage.tiling=VK_IMAGE_TILING_OPTIMAL; depthImage.usage=VK_IMAGE_USAGE_SAMPLED_BIT|VK_IMAGE_USAGE_STORAGE_BIT; depthImage.sharingMode=VK_SHARING_MODE_EXCLUSIVE;
        VmaAllocationCreateInfo allocation{}; allocation.usage=VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE;
        if(vmaCreateImage(allocator,&depthImage,&allocation,&linearDepthImage_,&linearDepthAllocation_,nullptr)!=VK_SUCCESS) throw std::runtime_error("Could not create GTAO linear-depth pyramid");
        VkImageViewCreateInfo fullView{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO}; fullView.image=linearDepthImage_; fullView.viewType=VK_IMAGE_VIEW_TYPE_2D; fullView.format=VK_FORMAT_R16_SFLOAT; fullView.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,linearDepthMipCount_,0,1}; if(vkCreateImageView(device_,&fullView,nullptr,&linearDepthView_)!=VK_SUCCESS) throw std::runtime_error("Could not create GTAO linear-depth view");
        linearDepthMipViews_.resize(linearDepthMipCount_); for(uint32_t mip=0;mip<linearDepthMipCount_;++mip) { auto view=fullView; view.subresourceRange.baseMipLevel=mip; view.subresourceRange.levelCount=1; if(vkCreateImageView(device_,&view,nullptr,&linearDepthMipViews_[mip])!=VK_SUCCESS) throw std::runtime_error("Could not create GTAO linear-depth mip view"); }
        VkSamplerCreateInfo depthSampler{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO}; depthSampler.magFilter=VK_FILTER_NEAREST; depthSampler.minFilter=VK_FILTER_NEAREST; depthSampler.mipmapMode=VK_SAMPLER_MIPMAP_MODE_NEAREST; depthSampler.addressModeU=depthSampler.addressModeV=depthSampler.addressModeW=VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE; depthSampler.maxLod=float(linearDepthMipCount_-1); if(vkCreateSampler(device_,&depthSampler,nullptr,&linearDepthSampler_)!=VK_SUCCESS) throw std::runtime_error("Could not create GTAO linear-depth sampler");
        const std::array<VkDescriptorSetLayoutBinding,2> computeBindings{{{0,VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,1,VK_SHADER_STAGE_COMPUTE_BIT,nullptr},{1,VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,1,VK_SHADER_STAGE_COMPUTE_BIT,nullptr}}};
        VkDescriptorSetLayoutCreateInfo computeLayout{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO}; computeLayout.bindingCount=uint32_t(computeBindings.size()); computeLayout.pBindings=computeBindings.data(); for(auto& layout:depthLayouts_) if(vkCreateDescriptorSetLayout(device_,&computeLayout,nullptr,&layout)!=VK_SUCCESS) throw std::runtime_error("Could not create GTAO depth descriptor layout");
        for(uint32_t i=0;i<2;++i) { VkPipelineLayoutCreateInfo info{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO}; info.setLayoutCount=1; info.pSetLayouts=&depthLayouts_[i]; VkPushConstantRange push{VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(LinearizeSettings)}; if(i==0){info.pushConstantRangeCount=1;info.pPushConstantRanges=&push;} if(vkCreatePipelineLayout(device_,&info,nullptr,&depthPipelineLayouts_[i])!=VK_SUCCESS) throw std::runtime_error("Could not create GTAO depth pipeline layout"); }
        const std::array<const char*,2> depthShaders{"shaders/gtao_linearize_depth.spv","shaders/gtao_depth_downsample.spv"}; for(uint32_t i=0;i<2;++i){const auto shader=Vkutil::loadShaderModule(device_,assets,depthShaders[i]); VkPipelineShaderStageCreateInfo stage{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO};stage.stage=VK_SHADER_STAGE_COMPUTE_BIT;stage.module=shader.get();stage.pName="main";VkComputePipelineCreateInfo info{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};info.stage=stage;info.layout=depthPipelineLayouts_[i];if(vkCreateComputePipelines(device_,VK_NULL_HANDLE,1,&info,nullptr,&depthPipelines_[i])!=VK_SUCCESS)throw std::runtime_error("Could not create GTAO depth compute pipeline");}
        const std::array<VkDescriptorPoolSize,2> depthPoolSizes{{{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,FramesInFlight+linearDepthMipCount_-1},{VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,FramesInFlight+linearDepthMipCount_-1}}}; VkDescriptorPoolCreateInfo depthPool{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};depthPool.maxSets=FramesInFlight+linearDepthMipCount_-1;depthPool.poolSizeCount=uint32_t(depthPoolSizes.size());depthPool.pPoolSizes=depthPoolSizes.data();if(vkCreateDescriptorPool(device_,&depthPool,nullptr,&depthDescriptorPool_)!=VK_SUCCESS)throw std::runtime_error("Could not create GTAO depth descriptor pool");
        std::array<VkDescriptorSetLayout,FramesInFlight> linearLayouts{};linearLayouts.fill(depthLayouts_[0]);VkDescriptorSetAllocateInfo linearAllocate{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};linearAllocate.descriptorPool=depthDescriptorPool_;linearAllocate.descriptorSetCount=FramesInFlight;linearAllocate.pSetLayouts=linearLayouts.data();if(vkAllocateDescriptorSets(device_,&linearAllocate,linearizeSets_.data())!=VK_SUCCESS)throw std::runtime_error("Could not allocate GTAO linearize sets");
        depthReduceSets_.resize(linearDepthMipCount_-1);std::vector<VkDescriptorSetLayout> reduceLayouts(linearDepthMipCount_-1,depthLayouts_[1]);VkDescriptorSetAllocateInfo reduceAllocate{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};reduceAllocate.descriptorPool=depthDescriptorPool_;reduceAllocate.descriptorSetCount=uint32_t(reduceLayouts.size());reduceAllocate.pSetLayouts=reduceLayouts.data();if(vkAllocateDescriptorSets(device_,&reduceAllocate,depthReduceSets_.data())!=VK_SUCCESS)throw std::runtime_error("Could not allocate GTAO depth reduction sets");
        for(uint32_t mip=1;mip<linearDepthMipCount_;++mip){VkDescriptorImageInfo src{linearDepthSampler_,linearDepthMipViews_[mip-1],VK_IMAGE_LAYOUT_GENERAL},dst{VK_NULL_HANDLE,linearDepthMipViews_[mip],VK_IMAGE_LAYOUT_GENERAL};std::array<VkWriteDescriptorSet,2>w{{{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,nullptr,depthReduceSets_[mip-1],0,0,1,VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,&src,nullptr,nullptr},{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,nullptr,depthReduceSets_[mip-1],1,0,1,VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,&dst,nullptr,nullptr}}};vkUpdateDescriptorSets(device_,uint32_t(w.size()),w.data(),0,nullptr);}
        const std::array<std::uint32_t, 5> counts{1, 2, 2, 4, 3};
        const std::array<const char*, 5> shaders{"shaders/gtao_raw.spv", "shaders/gtao_spatial.spv", "shaders/gtao_spatial.spv", "shaders/gtao_temporal.spv", "shaders/gtao_upsample.spv"};
        const std::array<std::uint32_t, 5> constantSizes{sizeof(RawSettings), sizeof(FilterSettings), sizeof(FilterSettings), sizeof(TemporalSettings), sizeof(UpsampleSettings)};
        for (std::size_t p = 0; p < pipelines_.size(); ++p) {
            std::vector<VkDescriptorSetLayoutBinding> bindings(counts[p]);
            for (std::uint32_t i = 0; i < counts[p]; ++i) bindings[i] = {i, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1, VK_SHADER_STAGE_FRAGMENT_BIT, nullptr};
            VkDescriptorSetLayoutCreateInfo li{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO}; li.bindingCount = counts[p]; li.pBindings = bindings.data();
            if (vkCreateDescriptorSetLayout(device_, &li, nullptr, &layouts_[p]) != VK_SUCCESS) throw std::runtime_error("Could not create GTAO descriptor layout");
            GraphicsPipelineOptions options{}; options.colorFormat = p == 4 ? FullAoFormat : p == 3 ? HistoryFormat : AoFormat; options.additionalColorFormat = p == 0 ? AuxiliaryFormat : VK_FORMAT_UNDEFINED; options.colorInitialLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL; options.colorFinalLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL; options.shader = shaders[p]; options.assetManager = &assets; options.pushConstantSize = constantSizes[p]; options.pushConstantStages = VK_SHADER_STAGE_FRAGMENT_BIT; options.cullMode = VK_CULL_MODE_NONE; options.depthTestEnable = VK_FALSE; options.depthWriteEnable = VK_FALSE; options.descriptorSetLayouts = {layouts_[p]}; pipelines_[p].create(device_, options);
            VkDescriptorPoolSize size{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, counts[p] * FramesInFlight}; VkDescriptorPoolCreateInfo pi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO}; pi.maxSets = FramesInFlight; pi.poolSizeCount = 1; pi.pPoolSizes = &size;
            if (vkCreateDescriptorPool(device_, &pi, nullptr, &pools_[p]) != VK_SUCCESS) throw std::runtime_error("Could not create GTAO descriptor pool");
            std::array<VkDescriptorSetLayout, FramesInFlight> setLayouts{}; setLayouts.fill(layouts_[p]);
            VkDescriptorSetAllocateInfo ai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO}; ai.descriptorPool = pools_[p]; ai.descriptorSetCount = FramesInFlight; ai.pSetLayouts = setLayouts.data();
            if (vkAllocateDescriptorSets(device_, &ai, sets_[p].data()) != VK_SUCCESS) throw std::runtime_error("Could not allocate GTAO descriptor set");
        }
        const std::array<VkImageView, 2> rawViews{raw_.imageView(), auxiliary_.imageView()};
        VkFramebufferCreateInfo rawFramebuffer{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO}; rawFramebuffer.renderPass=pipelines_[0].renderPass(); rawFramebuffer.attachmentCount=uint32_t(rawViews.size()); rawFramebuffer.pAttachments=rawViews.data(); rawFramebuffer.width=halfExtent_.width; rawFramebuffer.height=halfExtent_.height; rawFramebuffer.layers=1; if(vkCreateFramebuffer(device_,&rawFramebuffer,nullptr,&framebuffers_[0])!=VK_SUCCESS) throw std::runtime_error("Could not create GTAO raw framebuffer");
        const std::array<VkImageView, 5> views{spatial_.imageView(), filtered_.imageView(), history_[0].imageView(), history_[1].imageView(), full_.imageView()};
        for (std::size_t i = 0; i < views.size(); ++i) { const std::size_t framebufferIndex=i+1; VkFramebufferCreateInfo fb{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO}; fb.renderPass = pipelines_[i < 2 ? i + 1 : i < 4 ? 3 : 4].renderPass(); fb.attachmentCount = 1; fb.pAttachments = &views[i]; fb.width = i == 4 ? fullExtent_.width : halfExtent_.width; fb.height = i == 4 ? fullExtent_.height : halfExtent_.height; fb.layers = 1; if (vkCreateFramebuffer(device_, &fb, nullptr, &framebuffers_[framebufferIndex]) != VK_SUCCESS) throw std::runtime_error("Could not create GTAO framebuffer"); }
    } catch (...) { destroy(); throw; }
}

void GtaoPass::clearImages(const VkCommandBuffer cmd) {
    std::array<VkImageMemoryBarrier2, 7> b{}; const std::array<VkImage, 7> images{raw_.image(), auxiliary_.image(), spatial_.image(), filtered_.image(), history_[0].image(), history_[1].image(), full_.image()};
    for (std::size_t i=0;i<b.size();++i) { b[i]={VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2}; b[i].dstStageMask=VK_PIPELINE_STAGE_2_TRANSFER_BIT; b[i].dstAccessMask=VK_ACCESS_2_TRANSFER_WRITE_BIT; b[i].oldLayout=VK_IMAGE_LAYOUT_UNDEFINED; b[i].newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL; b[i].image=images[i]; b[i].subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1}; }
    VkDependencyInfo d{VK_STRUCTURE_TYPE_DEPENDENCY_INFO}; d.imageMemoryBarrierCount=uint32_t(b.size()); d.pImageMemoryBarriers=b.data(); vkCmdPipelineBarrier2(cmd,&d); VkClearColorValue white{{1.F,1.F,1.F,1.F}}; for(auto& barrier:b) vkCmdClearColorImage(cmd,barrier.image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,&white,1,&barrier.subresourceRange);
    for(auto& barrier:b) { barrier.srcStageMask=VK_PIPELINE_STAGE_2_TRANSFER_BIT; barrier.srcAccessMask=VK_ACCESS_2_TRANSFER_WRITE_BIT; barrier.dstStageMask=VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT; barrier.dstAccessMask=VK_ACCESS_2_SHADER_SAMPLED_READ_BIT; barrier.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL; barrier.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL; } vkCmdPipelineBarrier2(cmd,&d); initialized_=true;
}

void GtaoPass::draw(const VkCommandBuffer cmd, GraphicsPipeline& pipeline, const VkFramebuffer fb, const VkDescriptorSet set, const VkExtent2D extent, const void* constants, const std::uint32_t size) { VkClearValue clear{}; VkRenderPassBeginInfo begin{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO}; begin.renderPass=pipeline.renderPass(); begin.framebuffer=fb; begin.renderArea.extent=extent; begin.clearValueCount=1; begin.pClearValues=&clear; vkCmdBeginRenderPass(cmd,&begin,VK_SUBPASS_CONTENTS_INLINE); vkCmdBindPipeline(cmd,VK_PIPELINE_BIND_POINT_GRAPHICS,pipeline.handle()); vkCmdBindDescriptorSets(cmd,VK_PIPELINE_BIND_POINT_GRAPHICS,pipeline.layout(),0,1,&set,0,nullptr); vkCmdPushConstants(cmd,pipeline.layout(),VK_SHADER_STAGE_FRAGMENT_BIT,0,size,constants); const VkViewport vp{0,0,float(extent.width),float(extent.height),0,1}; const VkRect2D sc{{0,0},extent}; vkCmdSetViewport(cmd,0,1,&vp); vkCmdSetScissor(cmd,0,1,&sc); vkCmdDraw(cmd,3,1,0,0); vkCmdEndRenderPass(cmd); }

void GtaoPass::initialize(const VkCommandBuffer cmd) { if (!initialized_) clearImages(cmd); }

void GtaoPass::buildLinearDepth(const VkCommandBuffer cmd, const std::uint32_t frameIndex, const VkImageView depth, const VkSampler depthSampler, const Mat4& inverseProjection) {
    const VkImageLayout oldLayout=linearDepthInitialized_ ? VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL : VK_IMAGE_LAYOUT_UNDEFINED;
    VkImageMemoryBarrier2 begin{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2}; begin.dstStageMask=VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT; begin.dstAccessMask=VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT; begin.oldLayout=oldLayout; begin.newLayout=VK_IMAGE_LAYOUT_GENERAL; begin.image=linearDepthImage_; begin.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,linearDepthMipCount_,0,1}; VkDependencyInfo dependency{VK_STRUCTURE_TYPE_DEPENDENCY_INFO};dependency.imageMemoryBarrierCount=1;dependency.pImageMemoryBarriers=&begin;vkCmdPipelineBarrier2(cmd,&dependency);
    VkDescriptorImageInfo source{depthSampler,depth,VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL}, destination{VK_NULL_HANDLE,linearDepthMipViews_[0],VK_IMAGE_LAYOUT_GENERAL}; std::array<VkWriteDescriptorSet,2> writes{{{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,nullptr,linearizeSets_[frameIndex],0,0,1,VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,&source,nullptr,nullptr},{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,nullptr,linearizeSets_[frameIndex],1,0,1,VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,&destination,nullptr,nullptr}}}; vkUpdateDescriptorSets(device_,uint32_t(writes.size()),writes.data(),0,nullptr);
    vkCmdBindPipeline(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,depthPipelines_[0]); const VkDescriptorSet linearizeSet=linearizeSets_[frameIndex];vkCmdBindDescriptorSets(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,depthPipelineLayouts_[0],0,1,&linearizeSet,0,nullptr); const LinearizeSettings settings{inverseProjection.native()};vkCmdPushConstants(cmd,depthPipelineLayouts_[0],VK_SHADER_STAGE_COMPUTE_BIT,0,sizeof(settings),&settings);vkCmdDispatch(cmd,(fullExtent_.width+7)/8,(fullExtent_.height+7)/8,1);
    for(uint32_t mip=1;mip<linearDepthMipCount_;++mip){VkImageMemoryBarrier2 ready{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2};ready.srcStageMask=VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;ready.srcAccessMask=VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT;ready.dstStageMask=VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;ready.dstAccessMask=VK_ACCESS_2_SHADER_SAMPLED_READ_BIT;ready.oldLayout=VK_IMAGE_LAYOUT_GENERAL;ready.newLayout=VK_IMAGE_LAYOUT_GENERAL;ready.image=linearDepthImage_;ready.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,mip-1,1,0,1};dependency.pImageMemoryBarriers=&ready;vkCmdPipelineBarrier2(cmd,&dependency);vkCmdBindPipeline(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,depthPipelines_[1]);const VkDescriptorSet set=depthReduceSets_[mip-1];vkCmdBindDescriptorSets(cmd,VK_PIPELINE_BIND_POINT_COMPUTE,depthPipelineLayouts_[1],0,1,&set,0,nullptr);const uint32_t width=std::max(1u,fullExtent_.width>>mip),height=std::max(1u,fullExtent_.height>>mip);vkCmdDispatch(cmd,(width+7)/8,(height+7)/8,1);}
    VkImageMemoryBarrier2 complete{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2};complete.srcStageMask=VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT;complete.srcAccessMask=VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT;complete.dstStageMask=VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT;complete.dstAccessMask=VK_ACCESS_2_SHADER_SAMPLED_READ_BIT;complete.oldLayout=VK_IMAGE_LAYOUT_GENERAL;complete.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;complete.image=linearDepthImage_;complete.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,linearDepthMipCount_,0,1};dependency.pImageMemoryBarriers=&complete;vkCmdPipelineBarrier2(cmd,&dependency);linearDepthInitialized_=true;
}

void GtaoPass::record(const VkCommandBuffer cmd, const std::uint32_t frameIndex, const VkImageView depth, const VkSampler depthSampler, const VkImageView velocity, const VkSampler velocitySampler, const Mat4& inverseProjection, const bool useTemporalVelocity) {
    if (frameIndex >= FramesInFlight) throw std::out_of_range("Invalid GTAO frame slot");
    if (!initialized_) clearImages(cmd); const auto write = [&](uint32_t p, std::initializer_list<VkDescriptorImageInfo> images) { std::vector<VkWriteDescriptorSet> writes; uint32_t binding=0; for (const auto& image:images) { VkWriteDescriptorSet w{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET}; w.dstSet=sets_[p][frameIndex]; w.dstBinding=binding++; w.descriptorCount=1; w.descriptorType=VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER; w.pImageInfo=&image; writes.push_back(w); } vkUpdateDescriptorSets(device_,uint32_t(writes.size()),writes.data(),0,nullptr); };
    buildLinearDepth(cmd,frameIndex,depth,depthSampler,inverseProjection);
    const auto inverse=inverseProjection.native();
    write(0, {{linearDepthSampler_,linearDepthView_,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL}}); RawSettings raw{{1.F/inverse[0][0],1.F/inverse[1][1]},float(fullExtent_.width),float(fullExtent_.height),1.0F,1.0F}; draw(cmd,pipelines_[0],framebuffers_[0],sets_[0][frameIndex],halfExtent_,&raw,sizeof(raw));
    FilterSettings filter{1.F/float(halfExtent_.width),1.F/float(halfExtent_.height),2.0F,32.F,{1.F,0.F}};
    write(1, {{raw_.sampler(),raw_.imageView(),VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL},{auxiliary_.sampler(),auxiliary_.imageView(),VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL}}); draw(cmd,pipelines_[1],framebuffers_[1],sets_[1][frameIndex],halfExtent_,&filter,sizeof(filter));
    filter.direction={0.F,1.F};
    write(2, {{spatial_.sampler(),spatial_.imageView(),VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL},{auxiliary_.sampler(),auxiliary_.imageView(),VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL}}); draw(cmd,pipelines_[2],framebuffers_[2],sets_[2][frameIndex],halfExtent_,&filter,sizeof(filter));
    const uint32_t out=1U-historyIndex_;
    const VkDescriptorImageInfo velocityInfo = useTemporalVelocity
        ? VkDescriptorImageInfo{velocitySampler, velocity, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL}
        : VkDescriptorImageInfo{filtered_.sampler(), filtered_.imageView(), VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};
    write(3, {{filtered_.sampler(),filtered_.imageView(),VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL},{history_[historyIndex_].sampler(),history_[historyIndex_].imageView(),VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL},velocityInfo,{auxiliary_.sampler(),auxiliary_.imageView(),VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL}}); TemporalSettings temporal{1.F/float(halfExtent_.width),1.F/float(halfExtent_.height),useTemporalVelocity ? 0.88F : 0.F,0}; draw(cmd,pipelines_[3],framebuffers_[3+out],sets_[3][frameIndex],halfExtent_,&temporal,sizeof(temporal)); historyIndex_=out;
    write(4, {{history_[historyIndex_].sampler(),history_[historyIndex_].imageView(),VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL},{auxiliary_.sampler(),auxiliary_.imageView(),VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL},{linearDepthSampler_,linearDepthView_,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL}}); UpsampleSettings up{1.F/float(fullExtent_.width),1.F/float(fullExtent_.height),2.0F,0,1.F/float(halfExtent_.width),1.F/float(halfExtent_.height),0,0}; draw(cmd,pipelines_[4],framebuffers_[5],sets_[4][frameIndex],fullExtent_,&up,sizeof(up));
}

void GtaoPass::reset() noexcept { historyIndex_=0; initialized_=false; }
void GtaoPass::destroy() noexcept { if(device_) { for(auto fb:framebuffers_) if(fb) vkDestroyFramebuffer(device_,fb,nullptr); for(auto pool:pools_) if(pool) vkDestroyDescriptorPool(device_,pool,nullptr); for(auto layout:layouts_) if(layout) vkDestroyDescriptorSetLayout(device_,layout,nullptr); if(depthDescriptorPool_)vkDestroyDescriptorPool(device_,depthDescriptorPool_,nullptr);for(auto pipeline:depthPipelines_)if(pipeline)vkDestroyPipeline(device_,pipeline,nullptr);for(auto layout:depthPipelineLayouts_)if(layout)vkDestroyPipelineLayout(device_,layout,nullptr);for(auto layout:depthLayouts_)if(layout)vkDestroyDescriptorSetLayout(device_,layout,nullptr);if(linearDepthSampler_)vkDestroySampler(device_,linearDepthSampler_,nullptr);for(auto view:linearDepthMipViews_)if(view)vkDestroyImageView(device_,view,nullptr);if(linearDepthView_)vkDestroyImageView(device_,linearDepthView_,nullptr);if(linearDepthImage_)vmaDestroyImage(allocator_,linearDepthImage_,linearDepthAllocation_); } framebuffers_.fill(VK_NULL_HANDLE); pools_.fill(VK_NULL_HANDLE); layouts_.fill(VK_NULL_HANDLE);for(auto& perPass:sets_)perPass.fill(VK_NULL_HANDLE);for(auto& p:pipelines_)p.destroy();raw_.destroy();auxiliary_.destroy();spatial_.destroy();filtered_.destroy();for(auto& h:history_)h.destroy();full_.destroy();linearDepthImage_=VK_NULL_HANDLE;linearDepthAllocation_=VK_NULL_HANDLE;allocator_=VK_NULL_HANDLE;linearDepthView_=VK_NULL_HANDLE;linearDepthMipViews_.clear();linearDepthSampler_=VK_NULL_HANDLE;linearDepthMipCount_=0;linearDepthInitialized_=false;depthLayouts_.fill(VK_NULL_HANDLE);depthPipelineLayouts_.fill(VK_NULL_HANDLE);depthPipelines_.fill(VK_NULL_HANDLE);depthDescriptorPool_=VK_NULL_HANDLE;linearizeSets_.fill(VK_NULL_HANDLE);depthReduceSets_.clear();device_=VK_NULL_HANDLE;reset(); }
} // namespace Engine
