#pragma once

#include "Engine/Renderer/Geometry/Mesh.h"
#include "Engine/Renderer/Water/VirtualWaterTypes.h"
#include "Engine/Renderer/Water/WaterMaterial.h"

#include <array>
#include <cstdint>
#include <vector>

namespace Engine::Water {
    struct OceanDomainConfig final {
        std::array<float, ClipLevels> extents{OceanExtents};
        std::array<WaterGerstnerWave, 8> waves{defaultWaterWaves()};
        std::uint32_t waveCount{8};
        std::uint32_t bodyIndex{};
        std::uint32_t instanceIndex{};
        std::uint32_t pageBaseIndex{};
        std::uint32_t geometryLevelCount{GeometryClipLevels};
    };

    [[nodiscard]] float spectralWeight(float wavelength, float cellSize) noexcept;
    [[nodiscard]] bool pageIsInactive(std::uint32_t level, std::uint32_t x, std::uint32_t z) noexcept;
    [[nodiscard]] std::uint32_t pageStitchMask(std::uint32_t level,
                                               std::uint32_t x,
                                               std::uint32_t z) noexcept;

    /** Builds the 448 logical pages of one ocean. No geometry is duplicated here. */
    [[nodiscard]] std::vector<GPUVirtualWaterPage> buildOceanPageDomain(const OceanDomainConfig& config);

    /**
     * Builds one compact page grid and 16 index ranges. All ocean pages instance this same geometry.
     * Only 0/left/right/bottom/top masks are generated by the current clip hierarchy; the remaining
     * variants are kept valid for future neighbour-driven LOD selection.
     */
    [[nodiscard]] Mesh buildReusableOceanPageMesh();
}
