#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D sourceDepth;

layout(
set = 0,
binding = 1,
r32f
) uniform writeonly image2D destinationMip;

void main()
{
    ivec2 coordinate = ivec2(gl_GlobalInvocationID.xy);
    ivec2 destinationSize = imageSize(destinationMip);

    if (any(greaterThanEqual(coordinate, destinationSize)))
    {
        return;
    }

    float depth = texelFetch(sourceDepth, coordinate, 0).r;

    imageStore(
            destinationMip,
            coordinate,
            vec4(depth, 0.0, 0.0, 0.0)
    );
}