import GI.ddgi_gather_core;

[[vk::binding(20, 0)]] Sampler2D ddgiIrradiance;
[[vk::binding(21, 0)]] Sampler2D ddgiDistance;
[[vk::binding(22, 0)]] Sampler2D ddgiProbeData;
[[vk::binding(23, 0)]] Sampler2D ddgiIrradiance1;
[[vk::binding(24, 0)]] Sampler2D ddgiDistance1;
[[vk::binding(25, 0)]] Sampler2D ddgiProbeData1;
[[vk::binding(26, 0)]] Sampler2D ddgiIrradiance2;
[[vk::binding(27, 0)]] Sampler2D ddgiDistance2;
[[vk::binding(28, 0)]] Sampler2D ddgiProbeData2;
