// Generated by GamEngine. You can safely edit this script.
#pragma once
#include <Engine/Scripting/Script.h>

class CubeMovement final : public Engine::Script {
public:
    void onCreate() override {}
    void onUpdate(float deltaTime) override;
};
