// Generated by GamEngine. You can safely edit this script.
#include "CubeMovement.h"
#include <Engine/Scripting/ScriptRegistry.h>

ENGINE_REGISTER_SCRIPT(CubeMovement);

void CubeMovement::onUpdate(const float deltaTime) {
    constexpr float speed = 2.0f;
    actor().move({speed * deltaTime, 0.0f, 0.0f});
}
