find_package(Vulkan 1.4 REQUIRED)
# SDL3 is normally supplied by the active package manager.  Some existing
# developer installations bundle it with Vulkan SDK; keep that only as a
# discovery fallback instead of globally assigning SDL3_DIR.
find_package(SDL3 CONFIG QUIET)
if(NOT SDL3_FOUND)
    find_package(SDL3 CONFIG REQUIRED HINTS "$ENV{VULKAN_SDK}/cmake")
endif()
include(FetchContent)
set(PX_GENERATE_GPU_PROJECTS OFF CACHE BOOL "Build PhysX GPU projects" FORCE)
set(PX_GENERATE_STATIC_LIBRARIES ON CACHE BOOL "Build PhysX static libraries" FORCE)
set(PX_BUILDSNIPPETS OFF CACHE BOOL "Build PhysX snippets" FORCE)
set(PX_BUILDPVDRUNTIME OFF CACHE BOOL "Build PhysX PVD runtime" FORCE)
if(MSVC)
    set(NV_USE_STATIC_WINCRT ON CACHE BOOL "Use static Windows CRT in PhysX" FORCE)
endif()
if(WIN32 AND CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(PX_OUTPUT_ARCH "x64" CACHE INTERNAL "PhysX output architecture" FORCE)
endif()
FetchContent_Declare(NVIDIA_PhysX GIT_REPOSITORY https://github.com/NVIDIA-Omniverse/PhysX.git GIT_TAG 4f2103c GIT_SHALLOW TRUE SOURCE_SUBDIR physx)
FetchContent_MakeAvailable(NVIDIA_PhysX)
if(MSVC)
    function(gameengine_suppress_physx_c5054 directory)
        get_property(physx_targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
        foreach(physx_target IN LISTS physx_targets)
            get_target_property(physx_target_type ${physx_target} TYPE)
            if(NOT physx_target_type STREQUAL "INTERFACE_LIBRARY")
                target_compile_options(${physx_target} PRIVATE /Wv:18)
            endif()
        endforeach()
        get_property(physx_subdirectories DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
        foreach(physx_subdirectory IN LISTS physx_subdirectories)
            gameengine_suppress_physx_c5054("${physx_subdirectory}")
        endforeach()
    endfunction()
    gameengine_suppress_physx_c5054("${nvidia_physx_SOURCE_DIR}/physx")
endif()
FetchContent_Declare(DearImGui GIT_REPOSITORY https://github.com/ocornut/imgui.git GIT_TAG docking GIT_SHALLOW TRUE)
FetchContent_MakeAvailable(DearImGui)
add_library(DearImGui SHARED ${dearimgui_SOURCE_DIR}/imgui.cpp ${dearimgui_SOURCE_DIR}/imgui_demo.cpp ${dearimgui_SOURCE_DIR}/imgui_draw.cpp ${dearimgui_SOURCE_DIR}/imgui_tables.cpp ${dearimgui_SOURCE_DIR}/imgui_widgets.cpp ${dearimgui_SOURCE_DIR}/backends/imgui_impl_sdl3.cpp ${dearimgui_SOURCE_DIR}/backends/imgui_impl_vulkan.cpp)
target_include_directories(DearImGui PUBLIC ${dearimgui_SOURCE_DIR} ${dearimgui_SOURCE_DIR}/backends)
target_link_libraries(DearImGui PUBLIC SDL3::SDL3 Vulkan::Vulkan)
if(WIN32)
    set_target_properties(DearImGui PROPERTIES WINDOWS_EXPORT_ALL_SYMBOLS ON)
endif()
find_path(GLM_INCLUDE_DIR NAMES glm/glm.hpp HINTS "$ENV{VULKAN_SDK}/Include" REQUIRED)
find_path(VMA_INCLUDE_DIR NAMES vk_mem_alloc.h HINTS "$ENV{VULKAN_SDK}/Include/vma" REQUIRED)
