#include "Editor/Panels/EditorSceneSession.h"

#include "Engine/Renderer/Renderer.h"
#include "Engine/Scene/SceneSerializer.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <sstream>

std::filesystem::path EditorSceneSession::scenePath() {
    return std::filesystem::path{GAMEENGINE_SOURCE_DIR} / "Assets" / "Scenes" / "Editor.scene";
}

std::uint32_t EditorSceneSession::msaaSampleCount(const Engine::Renderer &renderer) {
    return renderer.antialiasingLevel() == Engine::AntialiasingLevel::MSAA2x
               ? 2U
               : renderer.antialiasingLevel() == Engine::AntialiasingLevel::MSAA4x
                     ? 4U
                     : 0U;
}

bool EditorSceneSession::setPlayMode(const bool play, Engine::ScenePreset &scene,
                                     std::string &snapshot, std::string &error, const std::uint32_t samples) {
    try {
        if (play) {
            std::ostringstream output;
            Engine::SceneSerializer::save(scene, output, samples);
            snapshot = std::move(output).str();
        } else {
            std::istringstream input{snapshot};
            Engine::SceneSerializer::load(scene, input);
            snapshot.clear();
        }
        error.clear();
        return true;
    } catch (const std::exception &exception) {
        error = exception.what();
        return false;
    }
}

bool EditorSceneSession::createCppScript(const std::string_view name, std::string &error) {
    if (name.empty() || !std::isalpha(static_cast<unsigned char>(name.front())) ||
        !std::ranges::all_of(name, [](const char c) {
            return std::isalnum(static_cast<unsigned char>(c)) || c == '_';
        })) {
        error = "Use a valid C++ class name.";
        return false;
    }
    const auto directory = std::filesystem::path{GAMEENGINE_SOURCE_DIR} / "Sandbox/Source/Scripts";
    const auto header = directory / (std::string{name} + ".h");
    const auto source = directory / (std::string{name} + ".cpp");
    if (std::filesystem::exists(header) || std::filesystem::exists(source)) {
        error = "Script already exists.";
        return false;
    }
    std::filesystem::create_directories(directory);
    std::ofstream h{header}, cpp{source};
    if (!h || !cpp) {
        error = "Could not create script files.";
        return false;
    }
    h << "// Generated by GamEngine. You can safely edit this script.\n"
            << "#pragma once\n#include <Engine/Scripting/Script.h>\n\nclass " << name
            << " final : public Engine::Script {\npublic:\n    void onCreate() override {}\n"
            << "    void onUpdate(float deltaTime) override { (void)deltaTime; }\n};\n";
    cpp << "// Generated by GamEngine. You can safely edit this script.\n#include \""
            << name << ".h\"\n#include <Engine/Scripting/ScriptRegistry.h>\n\nENGINE_REGISTER_SCRIPT("
            << name << ");\n";
    return static_cast<bool>(h) && static_cast<bool>(cpp);
}
